[microhil] Updated gh actions

diff --git a/.github/workflows/microhil_desktop_cc_checker.yml b/.github/workflows/microhil_desktop_cc_checker.yml
--- a/.github/workflows/microhil_desktop_cc_checker.yml
+++ b/.github/workflows/microhil_desktop_cc_checker.yml
@@ -20,7 +20,7 @@ jobs:
           modules_ok=0
           modules=($(find sw/ -type f -name '*.cc' -exec echo '{}' \;))
           for mod in "${modules[@]}"; do line_length=$(wc -L < "${mod}"); [[ $line_length -gt 80 ]] && modules_ok=1; done
-          [[ $modules_ok -eq 0 ]] && echo ::set-output name=status::success || echo ::set-output name=status::failure
+          [[ $modules_ok -eq 0 ]] && echo "action_state=success" >> "$GITHUB_ENV" || echo "action_state=failure" >> "$GITHUB_ENV"
       - name: Check number of lines in modules
         id: num_line_checker
         run: |
@@ -28,7 +28,7 @@ jobs:
           modules_ok=0
           modules=($(find sw/ -type f -name '*.cc' -exec echo '{}' \;))
           for mod in "${modules[@]}"; do line_numbers=$(wc -l < "${mod}"); [[ $line_numbers -gt 500 ]] && modules_ok=1; done
-          [[ $modules_ok -eq 0 ]] && echo ::set-output name=status::success || echo ::set-output name=status::failure
+          [[ $modules_ok -eq 0 ]] && echo "action_state=success" >> "$GITHUB_ENV" || echo "action_state=failure" >> "$GITHUB_ENV"
       - name: Check on failures
-        if: steps.long_line_checker.outputs.status == 'failure' || steps.num_line_checker.outputs.status == 'failure'
+        if: "$action_state" == "failure"
         run: exit 1
